# Structloc Configuration file

# Parameters for structure search
search:
  # Maximum distance (in blocks) to search for structures. Setting this to a very high value may cause performance issues.
  max-radius: 20000
  
  # Also search for unexplored structures
  find-unexplored: false

# Compass settings  
compass:
  # Update interval of the compass (in ticks, 20 ticks = 1 second)
  update-interval-ticks: 5
  
  # Compass display name
  name: "Structure Locator"

  # Whether to use animations for the compass needle (may cause performance issues on some clients)
  use-animations: true